keys:
  - &desant ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMOJoauZQLAdUyxVmB+oxNQK+LSQ1Y3/L///GjC+oQlG

creation_rules:
  - path_regex: secrets/desant\.yaml
    key_groups:
      - age:
          - *desant
