{ config, lib, ... }:

let
  inherit (lib)
    mkIf
    mkMerge
    mkEnableOption
    ;

  cfg = config.ceirios.boot.initrd;
in
{
  options.ceirios.boot.initrd = {
    tweaks = mkEnableOption "Initrd QOL" // {
      default = true;
    };

    compress = mkEnableOption "Use zstd" // {
      default = config.ceirios.profiles.workstation;
    };
  };

  config.boot.initrd = mkMerge [
    (mkIf cfg.tweaks {
      # this removes only the mandatory messages generated by the NixOS
      verbose = false;

      kernelModules = [
        "nvme"
        "xhci_pci"
        "ahci"
        "sd_mod"
        "dm_mod"
      ];

      availableKernelModules = [
        "vmd"
        "usbhid"
        "sd_mod"
        "sr_mod"
        "dm_mod"
        "uas"
        "usb_storage"
        "rtsx_usb_sdmmc"
        "rtsx_pci_sdmmc" # Realtek SD card interface
        "ata_piix"
        "virtio_pci"
        "virtio_scsi"
        "ehci_pci"
      ];
    })

    (mkIf cfg.compress {
      compressor = "zstd";
      compressorArgs = [
        "-19"
        "-T0"
      ];
    })
  ];
}
